//
// Created by bluet on 06/04/2021.
//

#ifndef CUDAUBUNTU_TANGENTIAL_FORCE_MINDLIN_VECT_CUH
#define CUDAUBUNTU_TANGENTIAL_FORCE_MINDLIN_VECT_CUH

#endif //CUDAUBUNTU_TANGENTIAL_FORCE_MINDLIN_VECT_CUH
